/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.palabras;

import mx.itson.resolver.resolver;





/**
 *
 * @author alumnog
 */
public class Palabras extends javax.swing.JFrame {

    /**
     * Creates new form curp
     */
    public Palabras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txfnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txfApaterno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txfAmaterno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jk = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnResultado = new javax.swing.JButton();
        txfDia = new javax.swing.JFormattedTextField();
        txfMes = new javax.swing.JFormattedTextField();
        txfAño = new javax.swing.JFormattedTextField();
        txcSexo = new javax.swing.JComboBox<>();
        txcEstado = new javax.swing.JComboBox<>();
        lblcurp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 1, 101)); // NOI18N
        jLabel5.setText("Curp");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setText("Nombre(s)*:");

        txfnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfnombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Primer apellido*:");

        jLabel3.setText("Segundo apellido:");

        jLabel4.setText("Día de nacimiento*:");

        jLabel6.setText("Mes de nacimiento*:");

        jk.setText("Año de nacimiento*:");

        jLabel7.setText("Estado*:");

        jLabel8.setText("Sexo*:");

        btnResultado.setText("Resultado");
        btnResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadoActionPerformed(evt);
            }
        });

        try {
            txfDia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txfMes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txfAño.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txfAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfAñoActionPerformed(evt);
            }
        });

        txcSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));

        txcEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chihuahua", "Distrito Federal", "Durango", "México", "Michoacán", "Morelos", "Nayarit", "Nuevo León", "Baja California Sur", "Campeche", "Coahuila", "Oaxaca", "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", "Aguascalientes", "Baja California", "Colima", "Chiapas Tlaxcala", "Veracruz", "Yucatán", "Zacatecas", "Nacido en el Extranjero", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco" }));

        lblcurp.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(txfAmaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(txfMes)
                    .addComponent(txcSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfApaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txfDia, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2)))
                    .addComponent(jk)
                    .addComponent(txfAño, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txcEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(btnResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(lblcurp, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfApaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfAmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jk))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txcSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txcEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnResultado)
                .addGap(18, 18, 18)
                .addComponent(lblcurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfnombreActionPerformed

    private void btnResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadoActionPerformed
       
        
        String nombre = txfnombre.getText().replace("Á", "A")
                .replace("É", "E")
                .replace("Í", "I")
                .replace("Ó", "O")
                .replace("Ú", "U")
                .replace("á", "a")
                .replace("é", "e")
                .replace("í", "i")
                .replace("ó", "o")
                .replace("ú", "u").toUpperCase();
        String primerApell = txfApaterno.getText().replace("Á", "A")
                .replace("É", "E")
                .replace("Í", "I")
                .replace("Ó", "O")
                .replace("Ú", "U")
                .replace("á", "a")
                .replace("é", "e")
                .replace("í", "i")
                .replace("ó", "o")
                .replace("ú", "u").toUpperCase();
        String segApell = txfAmaterno.getText().replace("Á", "A")
                .replace("É", "E")
                .replace("Í", "I")
                .replace("Ó", "O")
                .replace("Ú", "U")
                .replace("á", "a")
                .replace("é", "e")
                .replace("í", "i")
                .replace("ó", "o") 
                .replace("ú", "u").toUpperCase();
        String dia = txfDia.getText().replace(" ", "");
        String mes = txfMes.getText().replace(" ", ""); 
        String año = txfAño.getText().replace(" ", ""); 
        String estado = txcEstado.getActionCommand().toUpperCase();
        String sexo = txcSexo.getActionCommand().toString();
            
           char[] apellidoP = primerApell.toCharArray();
        char[] apellidoM = segApell.toCharArray();
        char[] letrasN = nombre.toCharArray();
        char[] dias = dia.toCharArray();
        char[] Mes = mes.toCharArray();
        char[] anos = año.toCharArray();
        char faño1= (char) (anos[2]);
        char faño2= (char) (anos[3]);
        char primeLetraP = apellidoP[0];
        char primeLetraM = apellidoM[0];
        char primeLetraN = letrasN[0];

      
        String sinmaterno = String.valueOf(apellidoM);
        if (sinmaterno == "") {
            sinmaterno = "X";
        } else {

            sinmaterno = String.valueOf(primeLetraM);

        }
        
        char vocalP = '0';
        for (int y = 1; apellidoP.length >= 0; y++) {
            if (apellidoP[y] == 'A' || apellidoP[y] == 'E' || apellidoP[y] == 'I'
                    || apellidoP[y] == 'O' || apellidoP[y] == 'U') {
                vocalP = apellidoP[y];
                break;

            }
        }
        char consonanteN = '0';
        for (int n = 1; letrasN.length >= 0; n++) {
            if (letrasN[n] == 'B' || letrasN[n] == 'C' || letrasN[n] == 'D' || letrasN[n] == 'F'
                    || letrasN[n] == 'G' || letrasN[n] == 'H' || letrasN[n] == 'J' || letrasN[n] == 'K'
                    || letrasN[n] == 'L' || letrasN[n] == 'M' || letrasN[n] == 'N' || apellidoP[n] == 'Ñ'
                    || letrasN[n] == 'P' || letrasN[n] == 'Q' || letrasN[n] == 'R' || letrasN[n] == 'S'
                    || letrasN[n] == 'T' || letrasN[n] == 'V' || letrasN[n] == 'W' || letrasN[n] == 'X'
                    || letrasN[n] == 'Y' || letrasN[n] == 'Z') {
                consonanteN = letrasN[n];
                break;
            }
        }

        char consonanteP = '0';
        for (int xd = 1; apellidoP.length >= 0; xd++) {
            if (apellidoP[xd] == 'B' || apellidoP[xd] == 'C' || apellidoP[xd] == 'D' || apellidoP[xd] == 'F'
                    || apellidoP[xd] == 'G' || apellidoP[xd] == 'H' || apellidoP[xd] == 'J' || apellidoP[xd] == 'K'
                    || apellidoP[xd] == 'L' || apellidoP[xd] == 'M' || apellidoP[xd] == 'N' || apellidoP[xd] == 'Ñ'
                    || apellidoP[xd] == 'P' || apellidoP[xd] == 'Q' || apellidoP[xd] == 'R' || apellidoP[xd] == 'S'
                    || apellidoP[xd] == 'T' || apellidoP[xd] == 'V' || apellidoP[xd] == 'W' || apellidoP[xd] == 'X'
                    || apellidoP[xd] == 'Y' || apellidoP[xd] == 'Z') {
                consonanteP = apellidoP[xd];
                break;

            }
        }
        char consonanteM = '0';
        if(apellidoM.equals("")){
          sinmaterno = String.valueOf(consonanteM);
          
        }else{

        for (int F = 1; apellidoM.length >= 0; F++) {
            if (apellidoM[F] == 'B' || apellidoM[F] == 'C' || apellidoM[F] == 'D' || apellidoM[F] == 'F'
                    || apellidoM[F] == 'G' || apellidoM[F] == 'H' || apellidoM[F] == 'J' || apellidoM[F] == 'K'
                    || apellidoM[F] == 'L' || apellidoM[F] == 'M' || apellidoM[F] == 'N' || apellidoM[F] == 'Ñ'
                    || apellidoM[F] == 'P' || apellidoM[F] == 'Q' || apellidoM[F] == 'R' || apellidoM[F] == 'S'
                    || apellidoM[F] == 'T' || apellidoM[F] == 'V' || apellidoM[F] == 'W' || apellidoM[F] == 'X'
                    || apellidoM[F] == 'Y' || apellidoM[F] == 'Z') {
                consonanteM = apellidoM[F];
                break;

            }
        }
        }

        
        int years = Integer.parseInt(año);
        String penultimo = "";
        if (years >= 2000) {
            penultimo = "A";
        } else {
            penultimo = "0";
        }
       String estadoMayus="";
       
       
        switch (estado) { 
    case "TABASCO":
        estadoMayus = "TC";
     break;
    case "NUEVO LEÓN":
        estadoMayus = "NL";
     break;
    case "NAYARIT":
        estadoMayus = "NT";
     break;
    case "MORELOS":
        estadoMayus = "MS";
     break;
    case "MICHOACÁN":
        estadoMayus = "MN";
     break;
    case "ESTADO DE MEXICO":
        estadoMayus = "MC";
     break;
    case "JALISCO":
        estadoMayus = "JC";
     break;
    case "HIDALGO":
        estadoMayus = "HG";
     break;
    case "GUERRERO":
        estadoMayus = "GR";
     break;
    case "GUANAJUATO":
        estadoMayus = "GT";
        break;
    case "DURANGO":
        estadoMayus = "DG";
     break;
    case "DISTRITO FEDERAL":
        estadoMayus = "DF";
        break;
    case "CHIHUAHUA":
        estadoMayus = "CH";
     break;
   case "CHIAPAS":
        estadoMayus = "CS";
     break;
     case "COLIMA":
        estadoMayus = "CM";
     break;
     case "COAHUILA":
        estadoMayus = "CL";
     break;
     case "CAMPECHE":
        estadoMayus = "CC";
     break;
     case "BAJA CALIFORNIA SUR":
        estadoMayus = "BS";
     break;
     case "BAJA CALIFORNIA":
        estadoMayus = "BC";
     break;
     case "AGUASCALIENTES":
        estadoMayus = "AS";
     break;
     case "QUINTANA ROO":
        estadoMayus = "QR";
     break;
     case "QUERÉTARO":
        estadoMayus = "QT";
     break;
     case "SINALOA":
        estadoMayus = "SL";
     break;
     case "SONORA":
        estadoMayus = "SR";
     break;
     case "TAMAULIPAS":
        estadoMayus = "TS";
     break;
     case "VERACRUZ":
        estadoMayus = "VZ";
     break;
     case "YUCATÁN":
        estadoMayus = "YN";
     break;
     case "SAN LUIS POTOSÍ":
        estadoMayus = "SP";
     break;
      case "OAXACA":
        estadoMayus = "OC";
     break;
      case "PUEBLA":
        estadoMayus = "PL";
     break;
      case "ZACATECAS":
        estadoMayus = "ZS";
     break;
      case "TLAXCALA":
        estadoMayus = "TL";
     break;
      case "NACIDO EXTRANJERO":
        estadoMayus = "NE";
     break;
     
    default:
  }
        
        
        if (sexo.equals("Mujer")) {
            sexo = "M";

        } else {
            sexo = "H";
        }

        
            
        
            
   
 String vocal = String.valueOf(vocalP);
            String ConsonanteN = String.valueOf(consonanteN);
            String ConsonanteP = String.valueOf(consonanteP);
            String ConsonanteM = String.valueOf(consonanteM);
            String datsof1=String.valueOf(faño1);
            String datsof2=String.valueOf(faño2);
            String años = datsof1+datsof2;
            String meses= String.valueOf(mes);
            String day= String.valueOf(dias);
            String fecha=años+meses+day;
            
           String curp = primeLetraP + vocal + primeLetraM + primeLetraN + fecha + sexo + estadoMayus + ConsonanteP 
                   + ConsonanteM + ConsonanteN + penultimo + "3";
           String curps= curp.toUpperCase();
           
          this.lblcurp.setText(curps);


        // TODO add your handling code here:
    }//GEN-LAST:event_btnResultadoActionPerformed

    private void txfAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfAñoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Palabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Palabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Palabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Palabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Palabras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jk;
    private javax.swing.JTextField lblcurp;
    private javax.swing.JComboBox<String> txcEstado;
    private javax.swing.JComboBox<String> txcSexo;
    private javax.swing.JTextField txfAmaterno;
    private javax.swing.JTextField txfApaterno;
    private javax.swing.JFormattedTextField txfAño;
    private javax.swing.JFormattedTextField txfDia;
    private javax.swing.JFormattedTextField txfMes;
    private javax.swing.JTextField txfnombre;
    // End of variables declaration//GEN-END:variables
}
